name: fikkton
description: A new Flutter project.
publish_to: 'none'  
 
version: 1.0.0+2

environment:
  sdk: '>=3.0.6 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  ionicons: ^0.2.2
  pin_code_fields: ^8.0.1
  youtube_player_flutter: ^8.1.2
  fl_chart: ^0.64.0
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  retry: ^3.1.2
  timeago: ^3.5.0
  firebase_messaging: ^14.7.2
  firebase_core: ^2.20.0
  flutter_local_notifications: ^16.1.0
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"
   
  flutter_lints: ^2.0.0

 
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
         
  